export type LegalSection = { title: string; body: string };
export const LEGAL_UPDATED = "September 5, 2026";

export const TERMS = {
  title: "Terms of Service",
  intro: "These Terms of Service govern your use of the Velta iOS app, prodvince.com, and beat marketplace. By browsing, creating an account, adding beats to a playlist, or buying a license, you agree to these Terms.",
  sections: [
    { title: "1. Who we are", body: "Velta (\u201cVelta,\u201d \u201cwe,\u201d \u201cus\u201d) operates a marketplace where producers can license beats and related audio at prodvince.com and in the Velta iOS app. Support: support@prodvince.com. Privacy: privacy@prodvince.com." },
    { title: "2. Eligibility", body: "You must be at least 13 years old (or the minimum digital-consent age in your country, if higher) to use the app. If you are under 18, you may only use Velta with a parent or guardian\u2019s permission. The app is not directed to children under 13." },
    { title: "3. Accounts", body: "Some features (purchases that sync to a store account, Studio uploads) require sign-in. You are responsible for activity on your account and for keeping credentials confidential. Demo or test logins, if shown, are for development only and must not be used to complete real payments.\n\n            Cart items, likes, playlists, and licenses stored on this iPhone remain on the device until you delete the app or clear that data." },
    { title: "4. Beat licenses \u2014 what you buy", body: "Buying a beat in Velta grants a license, not ownership of the underlying composition, master, or producer\u2019s brand unless the listing is sold as Exclusive and the listing says so.\n\n            Typical tiers (each beat may differ \u2014 the checkout screen controls):\n\n            \u2022 MP3 Lease \u2014 tagged MP3 for the uses and stream/video caps shown on the beat.\n            \u2022 WAV Lease \u2014 untagged WAV plus the uses and caps shown on the beat.\n            \u2022 Exclusive \u2014 exclusive rights as described on the beat. After an exclusive sale, Velta may remove the beat from the public store.\n\n            You may not redistribute untagged audio, resell the beat as a beat, claim you produced it, or use it beyond the listed caps and media types. Chargebacks, payment fraud, or license abuse may result in revocation without a replacement license." },
    { title: "5. Payments", body: "Prices are shown in USD unless stated otherwise. Checkout may be processed by:\n\n            \u2022 Whop (web checkout in regions where Apple allows external purchase of digital goods); and/or\n            \u2022 Apple In-App Purchase / StoreKit where Apple requires it.\n\n            Apple Pay in this app is not used to sell digital beat licenses. Payment processors (Whop, Apple, card networks) handle card data. Velta does not store full card numbers.\n\n            Taxes, currency conversion, and processor fees may apply. Refunds follow the processor\u2019s rules: Apple App Store purchases follow Apple\u2019s refund process; Whop checkouts follow Whop\u2019s refund policy and applicable law. Exclusive licenses are generally non-refundable once delivered, except where required by law." },
    { title: "6. Playlists, likes, and previews", body: "Playlists and likes are your personal collections. Previews may be watermarked or truncated. Preview playback does not grant a license. Do not record, rip, or redistribute preview audio." },
    { title: "7. Sellers and Studio", body: "If you upload or sell beats, you represent that you own or control the rights needed to license them, that the audio does not infringe others\u2019 rights, and that your listings are accurate. Velta may remove listings that appear unlawful, fraudulent, or in breach of these Terms. Payouts, if any, are handled by the connected payment provider (for example Whop) under that provider\u2019s terms." },
    { title: "8. Acceptable use", body: "You may not: reverse engineer the app except as allowed by law; scrape the catalog in a way that harms the service; upload malware; impersonate others; or use Velta to infringe copyrights, trademarks, or publicity rights." },
    { title: "9. Intellectual property", body: "The Velta name, app, and marketplace design are owned by Velta. Beat audio and artwork remain the property of the rights holder, licensed to you only as stated at purchase." },
    { title: "10. Disclaimer and limitation of liability", body: "The app and catalog are provided \u201cas is.\u201d Catalog availability, preview streams, and third-party checkout can fail. To the maximum extent permitted by law, Velta is not liable for indirect, incidental, or consequential damages, or for lost profits, lost licenses, or data loss. Our aggregate liability for a claim relating to the app is limited to the greater of USD $50 or the amount you paid Velta for the specific license giving rise to the claim in the 12 months before the claim." },
    { title: "11. Termination", body: "You may stop using the app at any time. We may suspend access for fraud, legal risk, or material breach. Licenses already granted remain subject to their original terms unless revoked for fraud or non-payment." },
    { title: "12. Changes", body: "We may update these Terms. The \u201cLast updated\u201d date will change. Continued use after an update means you accept the revised Terms. Material changes to licenses you already bought do not reduce rights you already paid for, except as required by law or to stop abuse." },
    { title: "13. Governing law", body: "These Terms are governed by the laws of the State of California, USA, excluding conflict-of-law rules, unless your local mandatory consumer law says otherwise. The United Nations Convention on Contracts for the International Sale of Goods does not apply." },
    { title: "14. Contact", body: "Questions about these Terms: support@prodvince.com" },
  ],
} as const;

export const PRIVACY = {
  title: "Privacy Policy",
  intro: "This Privacy Policy explains what Velta collects in the iOS marketplace app and on prodvince.com, how it is used, and the choices you have. It applies to the Velta app (bundle ID io.velta.marketplace) and the store at prodvince.com.",
  sections: [
    { title: "1. Controller", body: "Velta is the controller for personal data processed in the Velta marketplace iOS app and on prodvince.com. Contact: privacy@prodvince.com" },
    { title: "2. Data we process", body: "Depending on how you use the app, we may process:\n\n            \u2022 Account data \u2014 name, email, role (buyer/seller), and a session token when you sign in.\n            \u2022 On-device store data \u2014 cart, owned licenses, likes, playlists, recently viewed beats, and notification preference. This stays in iOS UserDefaults / app storage on your iPhone unless you sign in and a connected store syncs purchases.\n            \u2022 Purchase data \u2014 beat ID, license tier, amount, time, and a receipt or membership ID from Whop or Apple.\n            \u2022 Device identifiers \u2014 a device ID used by the Whop Checkout SDK to attach guest purchases and restore access.\n            \u2022 Usage needed to run the app \u2014 preview playback requests, catalog fetches, and checkout events used for fraud prevention and to deliver files.\n            \u2022 Support messages \u2014 if you email us, the content of that email.\n\n            We do not ask for your contacts, photos, microphone, camera, or precise location. We do not use the App Tracking Transparency framework to track you across other companies\u2019 apps and websites." },
    { title: "3. Payments", body: "Card numbers and Apple Pay tokens are processed by Whop and/or Apple, not stored by Velta. See Whop\u2019s privacy policy (whop.com) and Apple\u2019s privacy policy for their processing. We receive confirmation that a payment succeeded, a receipt or membership identifier, and the product/plan you bought." },
    { title: "4. Why we use data", body: "We use this data to: provide the catalog and previews; complete licenses; remember your bag, likes, and playlists; prevent fraud; provide support; and meet legal obligations. We do not sell personal data and we do not use it to train unrelated advertising profiles." },
    { title: "5. Sharing", body: "We share data only with:\n\n            \u2022 Whop \u2014 checkout, memberships, and payouts when you pay with Whop.\n            \u2022 Apple \u2014 App Store, StoreKit, or Apple Pay when those systems process a purchase.\n            \u2022 Hosting / CDN \u2014 to deliver catalog JSON, cover art, and audio previews.\n            \u2022 The law \u2014 if required by legal process, or to protect users, rights holders, or Velta against fraud and abuse.\n\n            Sellers may see that a license sold (and fulfillment details needed to deliver files), not your full payment card." },
    { title: "6. Retention", body: "On-device data remains until you delete the app or sign out (session only). Store-side purchase records are kept as long as needed for licenses, accounting, tax, and dispute handling, then deleted or anonymized. You can request deletion at privacy@prodvince.com. We may retain limited records where the law requires it (for example completed payments)." },
    { title: "7. Security", body: "We use HTTPS for network calls, scoped API keys for in-app checkout, and platform keychain/device storage where the SDK requires it. No method of transmission or storage is 100% secure." },
    { title: "8. Your rights", body: "Depending on where you live (including the EEA, UK, and California), you may have rights to access, correct, delete, or export personal data, and to object to or restrict certain processing. Email privacy@prodvince.com. You may also complain to a data protection authority. California residents: we do not \u201csell\u201d or \u201cshare\u201d personal information as those terms are used in the CCPA for cross-context behavioral advertising." },
    { title: "9. Children", body: "Velta is not directed to children under 13. We do not knowingly collect personal data from children under 13. If you believe we have, contact privacy@prodvince.com and we will delete it." },
    { title: "10. International transfers", body: "Our providers (including Whop and Apple) may process data in the United States and other countries. Where required, we rely on appropriate safeguards such as standard contractual clauses used by those providers." },
    { title: "11. Changes", body: "We may update this Policy. The \u201cLast updated\u201d date will change. Continued use after an update means you accept the revised Policy." },
    { title: "12. Contact", body: "privacy@prodvince.com \u00b7 support@prodvince.com\n            Public copy: https://prodvince.com/privacy" },
  ],
} as const;
